# 效能調校(Fine Tuning)作法，修改自
https://colab.research.google.com/github/huggingface/notebooks/blob/master/examples/text_classification.ipynb

In [1]:
! pip install datasets

Requirement already satisfied: datasets in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (5.0.1)
Requirement already satisfied: filelock in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from datasets) (3.32.2)
Requirement already satisfied: numpy>=1.17 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from datasets) (2.4.6)
Requirement already satisfied: pyarrow>=21.0.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from datasets) (3.0.5)
Requirement already satisfied: requests>=2.32.2 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from datasets) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from datasets) (4.70.0)
Requirement already satisfied: xxhash in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2026.6.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from datasets) (1.26.0)
Requirement already satisfied: packaging in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: anyio in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.24.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [2]:
import random
from typing import Any, Dict, cast

import datasets
import evaluate
import numpy as np
import pandas as pd
from IPython.display import HTML, display
from torch.utils.data import Dataset
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
)
from transformers.trainer_utils import BestRun, EvalPrediction

## 參數設定

## 定義GLUE所有任務(Task)

In [3]:
GLUE_TASKS = ["cola", "mnli", "mnli-mm", "mrpc", "qnli", "qqp", "rte", "sst2", "stsb", "wnli"]

## 指定任務為 cola

In [4]:
task = "cola"
# 預先訓練模型
model_checkpoint = "distilbert-base-uncased"
# 批量
batch_size = 16

## 載入資料集、效能衡量指標

In [5]:
actual_task = "mnli" if task == "mnli-mm" else task
# 載入資料集
dataset = datasets.load_dataset("nyu-mll/glue", actual_task)
# 載入效能衡量指標
metric = evaluate.load('glue', actual_task)

### dataset 資料型態為 [`DatasetDict`](https://huggingface.co/docs/datasets/package_reference/main_classes.html#datasetdict)

In [6]:
dataset

DatasetDict({
    train: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 8551
    })
    validation: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 1043
    })
    test: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 1063
    })
})

## 顯示第一筆內容

In [7]:
dataset["train"][0]

{'sentence': "Our friends won't buy this analysis, let alone the next one we propose.",
 'label': 1,
 'idx': 0}

## 定義隨機抽取數據函數

In [8]:
# 隨機抽取資料函數
def show_random_elements(dataset: datasets.Dataset, num_examples: int = 10) -> None:
    picks = []
    for _ in range(num_examples):
        pick = random.randint(0, len(dataset) - 1)
        while pick in picks:
            pick = random.randint(0, len(dataset) - 1)
        picks.append(pick)

    df = pd.DataFrame(dataset[picks])
    for column, typ in dataset.features.items():
        if isinstance(typ, datasets.ClassLabel):
            df[column] = df[column].transform(lambda i: typ.names[i])
    display(HTML(df.to_html()))

## 查看前30筆資料

In [9]:
df = pd.DataFrame(dataset["train"][:30])
df

                                             sentence  label  idx
0   Our friends won't buy this analysis, let alone...      1    0
1   One more pseudo generalization and I'm giving up.      1    1
2    One more pseudo generalization or I'm giving up.      1    2
3      The more we study verbs, the crazier they get.      1    3
4           Day by day the facts are getting murkier.      1    4
5                               I'll fix you a drink.      1    5
6                       Fred watered the plants flat.      1    6
7         Bill coughed his way out of the restaurant.      1    7
8                       We're dancing the night away.      1    8
9                     Herman hammered the metal flat.      1    9
10        The critics laughed the play off the stage.      1   10
11                              The pond froze solid.      1   11
12                       Bill rolled out of the room.      1   12
13             The gardener watered the flowers flat.      1   13
14                  The gardener watered the flowers.      1   14
15                Bill broke the bathtub into pieces.      1   15
16                            Bill broke the bathtub.      1   16
17                            They drank the pub dry.      1   17
18                                They drank the pub.      0   18
19             The professor talked us into a stupor.      1   19
20                           The professor talked us.      0   20
21                        We yelled ourselves hoarse.      1   21
22                               We yelled ourselves.      0   22
23                            We yelled Harry hoarse.      0   23
24                  Harry coughed himself into a fit.      1   24
25                             Harry coughed himself.      0   25
26                       Harry coughed us into a fit.      0   26
27            Bill followed the road into the forest.      1   27
28                  We drove Highway 5 from SD to SF.      1   28
29               Fred tracked the leak to its source.      1   29

## 隨機抽取10筆資料查看

In [10]:
show_random_elements(dataset["train"])

The metric is an instance of [`datasets.Metric`](https://huggingface.co/docs/datasets/package_reference/main_classes.html#datasets.Metric):

## 顯示效能衡量指標

In [11]:
metric

EvaluationModule(name: "glue", module_type: "metric", features: {'predictions': Value('int64'), 'references': Value('int64')}, usage: """
Compute GLUE evaluation metric associated to each GLUE dataset.
Args:
    predictions: list of predictions to score.
        Each translation should be tokenized into a list of tokens.
    references: list of lists of references for each translation.
        Each reference should be tokenized into a list of tokens.
Returns: depending on the GLUE subset, one or several of:
    "accuracy": Accuracy
    "f1": F1 score
    "pearson": Pearson Correlation
    "spearmanr": Spearman Correlation
    "matthews_correlation": Matthew Correlation
Examples:

    >>> glue_metric = evaluate.load('glue', 'sst2')  # 'sst2' or any of ["mnli", "mnli_mismatched", "mnli_matched", "qnli", "rte", "wnli", "hans"]
    >>> references = [0, 1]
    >>> predictions = [0, 1]
    >>> results = glue_metric.compute(predictions=predictions, references=references)
    >>> print(results)
    {'accuracy': 1.0}

    >>> glue_metric = evaluate.load('glue', 'mrpc')  # 'mrpc' or 'qqp'
    >>> references = [0, 1]
    >>> predictions = [0, 1]
    >>> results = glue_metric.compute(predictions=predictions, references=references)
    >>> print(results)
    {'accuracy': 1.0, 'f1': 1.0}

    >>> glue_metric = evaluate.load('glue', 'stsb')
    >>> references = [0., 1., 2., 3., 4., 5.]
    >>> predictions = [0., 1., 2., 3., 4., 5.]
    >>> results = glue_metric.compute(predictions=predictions, references=references)
    >>> print({"pearson": round(results["pearson"], 2), "spearmanr": round(results["spearmanr"], 2)})
    {'pearson': 1.0, 'spearmanr': 1.0}

    >>> glue_metric = evaluate.load('glue', 'cola')
    >>> references = [0, 1]
    >>> predictions = [0, 1]
    >>> results = glue_metric.compute(predictions=predictions, references=references)
    >>> print(results)
    {'matthews_correlation': 1.0}
""", stored examples: 0)

## 產生兩筆隨機亂數，測試效能衡量指標

In [12]:
fake_preds = np.random.randint(0, 2, size=(64,))
fake_labels = np.random.randint(0, 2, size=(64,))
metric.compute(predictions=fake_preds, references=fake_labels)

{'matthews_correlation': 0.11559657831495045}

Note that `load_metric` has loaded the proper metric associated to your task, which is:

- for CoLA: [Matthews Correlation Coefficient](https://en.wikipedia.org/wiki/Matthews_correlation_coefficient)
- for MNLI (matched or mismatched): Accuracy
- for MRPC: Accuracy and [F1 score](https://en.wikipedia.org/wiki/F1_score)
- for QNLI: Accuracy
- for QQP: Accuracy and [F1 score](https://en.wikipedia.org/wiki/F1_score)
- for RTE: Accuracy
- for SST-2: Accuracy
- for STS-B: [Pearson Correlation Coefficient](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient) and [Spearman's_Rank_Correlation_Coefficient](https://en.wikipedia.org/wiki/Spearman%27s_rank_correlation_coefficient)
- for WNLI: Accuracy

so the metric object only computes the one(s) needed for your task.

## 分詞

In [13]:
# 分詞
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint, use_fast=True)

You can directly call this tokenizer on one sentence or a pair of sentences:

## 測試兩筆資料，進行分詞

In [14]:
tokenizer("Hello, this one sentence!", "And this sentence goes with it.")

{'input_ids': [101, 7592, 1010, 2023, 2028, 6251, 999, 102, 1998, 2023, 6251, 3632, 2007, 2009, 1012, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

## 定義任務的資料集欄位

In [15]:
task_to_keys = {
    "cola": ("sentence", None),
    "mnli": ("premise", "hypothesis"),
    "mnli-mm": ("premise", "hypothesis"),
    "mrpc": ("sentence1", "sentence2"),
    "qnli": ("question", "sentence"),
    "qqp": ("question1", "question2"),
    "rte": ("sentence1", "sentence2"),
    "sst2": ("sentence", None),
    "stsb": ("sentence1", "sentence2"),
    "wnli": ("sentence1", "sentence2"),
}

## 測試第一筆資料

In [16]:
sentence1_key, sentence2_key = task_to_keys[task]
if sentence2_key is None:
    print(f"Sentence: {dataset['train'][0][sentence1_key]}")
else:
    print(f"Sentence 1: {dataset['train'][0][sentence1_key]}")
    print(f"Sentence 2: {dataset['train'][0][sentence2_key]}")

Sentence: Our friends won't buy this analysis, let alone the next one we propose.

## 測試 5 筆資料分詞

In [17]:
def preprocess_function(examples: Dict[str, Any]) -> Dict[str, Any]:
    if sentence2_key is None:
        return tokenizer(examples[sentence1_key], truncation=True)
    return tokenizer(examples[sentence1_key], examples[sentence2_key], truncation=True)


preprocess_function(dataset['train'][:5])

{'input_ids': [[101, 2256, 2814, 2180, 1005, 1056, 4965, 2023, 4106, 1010, 2292, 2894, 1996, 2279, 2028, 2057, 16599, 1012, 102], [101, 2028, 2062, 18404, 2236, 3989, 1998, 1045, 1005, 1049, 3228, 2039, 1012, 102], [101, 2028, 2062, 18404, 2236, 3989, 2030, 1045, 1005, 1049, 3228, 2039, 1012, 102], [101, 1996, 2062, 2057, 2817, 16025, 1010, 1996, 13675, 16103, 2121, 2027, 2131, 1012, 102], [101, 2154, 2011, 2154, 1996, 8866, 2024, 2893, 14163, 8024, 3771, 1012, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

To apply this function on all the sentences (or pairs of sentences) in our dataset, we just use the `map` method of our `dataset` object we created earlier. This will apply the function on all the elements of all the splits in `dataset`, so our training, validation and testing data will be preprocessed in one single command.

In [18]:
# 將所有資料進行分詞
encoded_dataset = dataset.map(preprocess_function, batched=True)

Map:   0%|          | 0/8551 [00:00<?, ? examples/s]

Map:   0%|          | 0/1043 [00:00<?, ? examples/s]

Map:   0%|          | 0/1063 [00:00<?, ? examples/s]

## 效能微調(Fine tuning)，先加載預先訓練的模型

In [19]:
# 載入預先訓練的模型
num_labels = 3 if task.startswith("mnli") else 1 if task == "stsb" else 2
model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=num_labels)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

## 定義訓練參數，可參閱 [`TrainingArguments`](https://huggingface.co/transformers/main_classes/trainer.html#transformers.TrainingArguments)

In [20]:
metric_name = "pearson" if task == "stsb" else "matthews_correlation" if task == "cola" else "accuracy"

args = TrainingArguments(
    "test-glue",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    num_train_epochs=5,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model=metric_name,
)

## 定義效能衡量指標計算的函數

In [21]:
def compute_metrics(eval_pred: EvalPrediction) -> Dict[str, float]:
    predictions, labels = eval_pred
    predictions = cast(np.ndarray, predictions)
    if task != "stsb":
        predictions = np.argmax(predictions, axis=1)
    else:
        predictions = predictions[:, 0]
    result = metric.compute(predictions=predictions, references=labels)
    assert result is not None
    return result

## 定義訓練者(Trainer)物件

In [22]:
validation_key = (
    "validation_mismatched" if task == "mnli-mm" else "validation_matched" if task == "mnli" else "validation"
)

trainer = Trainer(
    model,
    args,
    train_dataset=encoded_dataset["train"],
    eval_dataset=encoded_dataset[validation_key],
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)

## 模型訓練

In [23]:
trainer.train()

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=2675, training_loss=0.2696611764497846, metrics={'train_runtime': 541.7671, 'train_samples_per_second': 78.918, 'train_steps_per_second': 4.938, 'total_flos': 229000686898068.0, 'train_loss': 0.2696611764497846, 'epoch': 5.0})

## 模型評估

In [24]:
trainer.evaluate()

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 0.8188051581382751,
 'eval_matthews_correlation': 0.5500793243102087}

## 模型存檔

In [25]:
trainer.save_model('cola')

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

## 預測

In [26]:
class SimpleDataset(Dataset):
    def __init__(self, tokenized_texts: Any) -> None:
        self.tokenized_texts = tokenized_texts

    def __len__(self) -> int:
        return len(self.tokenized_texts["input_ids"])

    def __getitem__(self, idx: int) -> Dict[str, Any]:
        return {k: v[idx] for k, v in self.tokenized_texts.items()}


texts = ["Hello, this one sentence!", "And this sentence goes with it."]
tokenized_texts = tokenizer(texts, padding=True, truncation=True)
new_dataset = SimpleDataset(tokenized_texts)
trainer.predict(new_dataset)

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

PredictionOutput(predictions=array([[-1.3833233,  1.2554325],
       [-2.8858545,  2.791675 ]], dtype=float32), label_ids=None, metrics={'test_runtime': 0.1675, 'test_samples_per_second': 11.94, 'test_steps_per_second': 5.97})

In [27]:
tokenized_texts = tokenizer(
    ["They drank the pub.", "The professor talked us into a stupor."], padding=True, truncation=True
)
new_dataset = SimpleDataset(tokenized_texts)
trainer.predict(new_dataset)

PredictionOutput(predictions=array([[-2.8101385,  2.7338908],
       [-2.9691381,  2.8696914]], dtype=float32), label_ids=None, metrics={'test_runtime': 0.025, 'test_samples_per_second': 79.958, 'test_steps_per_second': 39.979})

In [28]:
tokenized_texts = tokenizer(["Hello there!", "This is another text"], padding=True, truncation=True)
new_dataset = SimpleDataset(tokenized_texts)
trainer.predict(new_dataset)

PredictionOutput(predictions=array([[-2.697493 ,  2.5639   ],
       [-2.6228921,  2.5515208]], dtype=float32), label_ids=None, metrics={'test_runtime': 0.2053, 'test_samples_per_second': 9.74, 'test_steps_per_second': 4.87})

To see how your model fared you can compare it to the [GLUE Benchmark leaderboard](https://gluebenchmark.com/leaderboard).

## Hyperparameter search

The `Trainer` supports hyperparameter search using [optuna](https://optuna.org/) or [Ray Tune](https://docs.ray.io/en/latest/tune/). For this last section you will need either of those libraries installed, just uncomment the line you want on the next cell and run it.

In [29]:
! pip install optuna
! pip install ray[tune]

Requirement already satisfied: optuna in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from optuna) (1.19.1)
Requirement already satisfied: colorlog in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from optuna) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from optuna) (4.70.0)
Requirement already satisfied: PyYAML in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from alembic>=1.5.0->optuna) (1.4.1)
Requirement already satisfied: typing-extensions>=4.12 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Requirement already satisfied: ray[tune] in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (2.56.1)
Requirement already satisfied: click>=7.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from ray[tune]) (8.4.2)
Requirement already satisfied: filelock in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from ray[tune]) (3.32.2)
Requirement already satisfied: jsonschema in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from ray[tune]) (4.26.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from ray[tune]) (1.2.1)
Requirement already satisfied: packaging>=24.2 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from ray[tune]) (26.2)
Requirement already satisfied: protobuf>=3.20.3 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from ray[tune]) (7.35.1)
Requirement already satisfied: pyyaml in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from ray[tune]) (6.0.3)
Requirement already satisfied: requests in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from ray[tune]) (2.34.2)
Requirement already satisfied: pandas in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from ray[tune]) (3.0.5)
Requirement already satisfied: tensorboardX>=1.9 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from ray[tune]) (2.6.5)
Requirement already satisfied: pyarrow>=17.0.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from ray[tune]) (24.0.0)
Requirement already satisfied: fsspec in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from ray[tune]) (2026.6.0)
Requirement already satisfied: pydantic<3,>=2.5.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from ray[tune]) (2.13.4)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from pydantic<3,>=2.5.0->ray[tune]) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from pydantic<3,>=2.5.0->ray[tune]) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from pydantic<3,>=2.5.0->ray[tune]) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from pydantic<3,>=2.5.0->ray[tune]) (0.4.2)
Requirement already satisfied: numpy in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from tensorboardX>=1.9->ray[tune]) (2.4.6)
Requirement already satisfied: attrs>=22.2.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from jsonschema->ray[tune]) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from jsonschema->ray[tune]) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from jsonschema->ray[tune]) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from jsonschema->ray[tune]) (2026.6.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from pandas->ray[tune]) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->ray[tune]) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from requests->ray[tune]) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from requests->ray[tune]) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from requests->ray[tune]) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages (from requests->ray[tune]) (2026.7.22)

During hyperparameter search, the `Trainer` will run several trainings, so it needs to have the model defined via a function (so it can be reinitialized at each new run) instead of just having it passed. We jsut use the same function as before:

In [30]:
def model_init() -> Any:
    return AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=num_labels)

And we can instantiate our `Trainer` like before:

In [31]:
trainer = Trainer(
    model_init=model_init,
    args=args,
    train_dataset=encoded_dataset["train"],
    eval_dataset=encoded_dataset[validation_key],
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

The method we call this time is `hyperparameter_search`. Note that it can take a long time to run on the full dataset for some of the tasks. You can try to find some good hyperparameter on a portion of the training dataset by replacing the `train_dataset` line above by:
```python
train_dataset = encoded_dataset["train"].shard(index=1, num_shards=10) 
```
for 1/10th of the dataset. Then you can run a full training on the best hyperparameters picked by the search.

In [32]:
best_run = trainer.hyperparameter_search(n_trials=10, direction="maximize")
assert isinstance(best_run, BestRun)

[I 2026-08-21 16:15:25,043] A new study created in memory with name: no-name-20aabb02-f927-4c44-b72c-8c43d2ec128a

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-08-21 16:51:38,283] Trial 0 finished with value: 0.41374866816430894 and parameters: {'learning_rate': 1.1955718289589301e-06, 'num_train_epochs': 5, 'seed': 26, 'per_device_train_batch_size': 4}. Best is trial 0 with value: 0.41374866816430894.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-08-21 16:57:53,509] Trial 1 finished with value: 0.5300972900950771 and parameters: {'learning_rate': 8.721678842948556e-05, 'num_train_epochs': 3, 'seed': 28, 'per_device_train_batch_size': 64}. Best is trial 1 with value: 0.5300972900950771.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-08-21 17:01:35,835] Trial 2 finished with value: 0.5062113421265578 and parameters: {'learning_rate': 4.455781842123646e-05, 'num_train_epochs': 2, 'seed': 18, 'per_device_train_batch_size': 16}. Best is trial 1 with value: 0.5300972900950771.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-08-21 17:06:29,510] Trial 3 finished with value: 0.3750769421645332 and parameters: {'learning_rate': 2.0703546490493967e-06, 'num_train_epochs': 5, 'seed': 30, 'per_device_train_batch_size': 32}. Best is trial 1 with value: 0.5300972900950771.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-08-21 17:07:42,080] Trial 4 finished with value: 0.0 and parameters: {'learning_rate': 2.593225293771976e-06, 'num_train_epochs': 2, 'seed': 11, 'per_device_train_batch_size': 64}. Best is trial 1 with value: 0.5300972900950771.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)
[I 2026-08-21 17:09:26,593] Trial 5 pruned.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-08-21 17:12:54,347] Trial 6 finished with value: 0.4392663684224782 and parameters: {'learning_rate': 1.744903350122817e-05, 'num_train_epochs': 1, 'seed': 29, 'per_device_train_batch_size': 8}. Best is trial 1 with value: 0.5300972900950771.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

[I 2026-08-21 17:14:40,414] Trial 7 pruned.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-08-21 17:28:13,783] Trial 8 finished with value: 0.48877941077800513 and parameters: {'learning_rate': 1.2138198659672566e-05, 'num_train_epochs': 2, 'seed': 13, 'per_device_train_batch_size': 4}. Best is trial 1 with value: 0.5300972900950771.

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[I 2026-08-21 17:41:52,584] Trial 9 finished with value: 0.4936257221427369 and parameters: {'learning_rate': 2.5251020501648355e-05, 'num_train_epochs': 4, 'seed': 17, 'per_device_train_batch_size': 8}. Best is trial 1 with value: 0.5300972900950771.

The `hyperparameter_search` method returns a `BestRun` objects, which contains the value of the objective maximized (by default the sum of all metrics) and the hyperparameters it used for that run.

In [33]:
best_run

BestRun(run_id='1', objective=0.5300972900950771, hyperparameters={'learning_rate': 8.721678842948556e-05, 'num_train_epochs': 3, 'seed': 28, 'per_device_train_batch_size': 64}, run_summary=None)

You can customize the objective to maximize by passing along a `compute_objective` function to the `hyperparameter_search` method, and you can customize the search space by passing a `hp_space` argument to `hyperparameter_search`. See this [forum post](https://discuss.huggingface.co/t/using-hyperparameter-search-in-trainer/785/10) for some examples.

To reproduce the best training, just set the hyperparameters in your `TrainingArgument` before creating a `Trainer`:

In [34]:
for n, v in best_run.hyperparameters.items():
    setattr(trainer.args, n, v)

trainer.train()

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/Users/rikenmi/Work/study/python/PyTorch_Book/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=3207, training_loss=0.5425681627759467, metrics={'train_runtime': 621.2677, 'train_samples_per_second': 41.291, 'train_steps_per_second': 5.162, 'total_flos': 120777926900772.0, 'train_loss': 0.5425681627759467, 'epoch': 3.0})

Don't forget to [upload your model](https://huggingface.co/transformers/model_sharing.html) on the [Model Hub](https://huggingface.co/models). You can then use it only to generate results like the one shown in the first picture of this notebook!